[package]
name = "rocky28447/flipper"
description = "A motion library for Roblox forked to add support for Tweens"
license = "MIT"
authors = ["Reselim", "AlreadyPro", "Rocky28447"]
version = "2.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "src"]

[dependencies]
Signal = "sleitnick/signal@^1.2"